### ISSUE TITLE
Implement localization infrastructure to translate strings using Pontoon

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockwise/lockwise-ios#440]
In service to localization support, the localizable string bundles need to include the latest strings present in code and views.

## Todo

* [x] Ensure existing LocalizableStrings in `Common/Resources/Constants.swift` are present in `Common/Resources/Strings/en.lproj/en.lproj/Localizable.strings` file 
* [x] Ensure all displayed strings from Storyboards are present in `Storyboard/en.lproj/*.strings` files
* [x] ~Document steps a localizer takes to provide translations~ done via Pontoon
* [x] Document steps to export strings and submit PR to l10n repo #960 
* [x] Create placeholders and make the languages available to Pontoon: de, es, fr, it
* [x] Document steps to import strings
* [x] Actually import and test the strings

## Resources

- https://github.com/mozilla-mobile/ios-l10n-scripts
- https://developer.mozilla.org/en-US/docs/Mozilla/Implementing_Pontoon_in_a_Mozilla_website

**Comment by linuxwolf** [comment]
Added this issue to track progress on localization work.

**Comment by xerta555** [comment]
Hello, i have translate directly all indicated files referenced in your link.
I am not a pro in iOS, but in the first file, i don't understand the meaning of the sentences after `, comment:`.

Maybe it wasn't necessary to translate these sentences, in this case simple copy and paste between the initial/official repo and my changes will suffice, or maybe i did things well.

As i don't see where my commit have been referenced, you could find them in commits list of my fork: [here](https://github.com/xerta555/lockbox-ios/commits/master).

**Comment by devinreams** [comment]
@xerta555 Thank you for your work helping us translate these strings!

To help make it easier for people to contribute translations, we are going to work on the infrastructure needed to export strings and load them into our translation tool (Pontoon) soon.

We do not expect to launch with any language _other than_ English at first, but do hope to have this infrastructure ready later this summer. We'll then provide instructions on how to submit translations.

Thank you again for your branch and changes, we'll be sure to reference that when we're ready to incorporate other languages. 🙇

**Comment by devinreams** [comment]
Per @sandysage we will not do this until after all our content requirements get sorted out. Moving this and #207 back out of the backlog.

**Comment by devinreams** [comment]
Strings have been exported, translated in Pontoon, and now re-imported into the project here:
https://github.com/mozilla-lockwise/lockwise-ios/pull/997

![Screen Shot 2019-05-21 at 10 50 02 AM](https://user-images.githubusercontent.com/49511/58115176-bd32d400-7bb6-11e9-8231-8440e450ce63.png)
